### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by SOF3**
For convenience of pulling from composer for phpstan

### CODE REVIEW

**Comment by dktapps** [comment]
Is there a reason not to just handle this the same way as any other virion?

**Comment by SOF3** [comment]
I'm not sure how any other virion is handled. Isn't phpstan + compose rthe standard way to setup this locally?

**Comment by dktapps** [comment]
I don't know. Virions are your domain.

**Comment by SOF3** [comment]
phpstan is not my domain though. Afaik it's not trivial to setup phpstan for projects that depend on other plugins or virions. Composer might be a good solution to this, but I don't know if that's what everyone is doing.

**Comment by dktapps** [comment]
It's easy enough, just add the src directory to `scanDirectories`.

**Comment by SOF3** [comment]
Yes, but you need to have cloned it locally first. This doesn't feel very standardized.

**Comment by dktapps** [comment]
I thought there was a procedure for installing virions locally?

**Comment by SOF3** [comment]
Not automatically. You would have to download them one by one on a CI environment. This is due to the unfortunate design choice that virions are declared in a Poggit-specific file.

**Comment by dktapps** [comment]
I thought that's what DEVirion was for ...
It seems to me like your purpose would be better served by improving the virion installation process instead of littering every virion repository with composer.json files.

**Comment by SOF3** [comment]
> I thought that's what DEVirion was for ...
> It seems to me like your purpose would be better served by improving the virion installation process instead of littering every virion repository with composer.json files.

Nope, devirion just loads virions from the virions folder.

**Comment by dktapps** [comment]
I don't think composer.lock should be committed here

**Comment by SOF3** [comment]
what's the general rule? no composer.lock for libraries?

**Comment by dktapps** [comment]
Yes, it's not used for libraries anyway. It's only useful for the top-level project where `composer install` is run, to lock dependencies to a known state.

**Comment by SOF3** [comment]
Obsoleted by #15

**Pull request closed without merging**
